ARG BIOTHINGS_VERSION
FROM biothings:${BIOTHINGS_VERSION}

RUN pip install ipython

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y ne \
        && rm -rf /var/lib/apt/lists/*

USER biothings
