services:
  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
    environment:
      - discovery.type=single-node
    ulimits: 
      nofile:
        soft: 32000
        hard: 65535
    ports:
      - "9200:9200"
  cerebro:
    image: lmenezes/cerebro:latest
    ports:
      - 9000:9000  # 9000 default, it was like this before as well
  webapp:
    image: biothings/biothings-webapp:master
    ports:
      - "8080:80"
  biothings:
    image: biothings/biothings-standalone-hub:master
    environment: 
      - SRC_URI=mongodb://username:psword@hostname:12345
    ports:
      - "7022:7022"
      - "7080:7080"
    volumes: 
      - data:/data
volumes: 
  data:
